application: 0-gaya
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: htdocs/favicon.ico
  upload: htdocs/favicon\.ico

- url: .*/robots.txt
  static_files: htdocs/robots.txt
  upload: htdocs/robots\.txt

- url: /css
  static_dir: htdocs/css

- url: /img
  static_dir: htdocs/img

- url: /js
  static_dir: htdocs/js

- url: /(.*\.html)
  static_files: htdocs/\1
  upload: htdocs/(.*\.html)

- url: /oogiri/.*
  script: oogiri.py

- url: .*
  script: main.py


builtins:
- remote_api: on
- datastore_admin: on
